apiVersion: apps/v1
kind: Deployment
metadata:
  name: job
  labels:
    app: job
spec:
  replicas: 1
  template:  #pod ka specification
    metadata:
      name: job
      labels:
        app: job
    spec:
      containers:
      - name: job
        image: jiya2802/jobms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
      restartPolicy: Always
  selector:
    matchLabels:
      app: job
